### ISSUE TITLE
Documentation/feature request for cluster shapes

### ISSUE THREAD

**Issue by dpcook** [marcovarrone/cellcharter#14]
### Description of feature

Thanks for developing CellCharter--have been trying it out with CosMx data and it's been great!

I was wondering if you could provide additional information assessing and visualizing cluster shapes as done in the manuscript. I think I found the functionality for the other downstream analyses described in Fig 1B, but if you ever have the time, adding them to the end of the existing tutorial would be helpful.

**Comment by marcovarrone** [comment]
Hi @dpcook, thank you for testing CellCharter, I am happy to see that people are interested!

Sorry for the time to answer but a clean implementation of the shapes analyses required some work because of the integration with [spatialdata](https://spatialdata.scverse.org/en/latest/).

By tomorrow I am going to finish the implementation (I linked the PR and it will close this issue once it's merged) and include some examples in the CODEX tutorial.

I hope you will like it :)
