### ISSUE TITLE
Confirmation of Utilizing Multiple GPUs and Re-training Upon Addition of Data

### ISSUE THREAD

**Issue by ayumatsubo** [marcovarrone/cellcharter#21]
Dear CellCharter Developers,

Thank you very much for this wonderful tool. When I tried CellCharter, it captures the tissue structure quite well.

As we plan to handle the large-scale data in the future, I have a question and a request.

1. Is it possible to perform training using multiple GPUs for CellCharter?
2. When new data is added, is it necessary to restart the all training process from the beginning? Can we use the results of the previous training to annotate clusters for the new data? If such a function is not available, it would be extremely helpful if you could consider adding this function.
3. Is it possible to extract features or create a hierarchal structure based on the obtained clusters depending on the number of clusters?

Thank you once again for this fantastic tool.

Ayumu

**Comment by marcovarrone** [comment]
Hi @ayumatsubo 
Thank you very much! It's always rewarding to see people liking it :)

1. Yes, because both the dimensionality reduction and clustering steps are based on the PyTorch Lightning framework. For the `cellcharter.tl.Cluster` class, for example, you can pass to the [`trainer_params`](https://cellcharter.readthedocs.io/en/latest/generated/cellcharter.tl.Cluster.html#cellcharter-tl-cluster) parameter, the same parameters of the PyTorch Lightning [Trainer](https://lightning.ai/docs/pytorch/stable/common/trainer.html#trainer-class-api). Check their documentation to understand better how to do it. I personally never tested it, so any feedback is welcome!
2. In theory you don't need to retrain everything. `cellcharter.tl.Cluster` has the `fit` method to fit the clustering algorithm on the data and then you can use the `predict` method on any other data. I also never tested this, so let me know if it works properly. Keep in mind that if there are strong batch effects or unseen neighborhoods between cells in the new data, the results may not be the best.
3. That would be very interesting. I never implemented anything official for the hierarchical structure, but I never found a very good way to visualize it. But it's certainly something I would like to add. Regarding the features, do you have anything specific in mind?

Let me know if you need anything else!

**Comment by ayumatsubo** [comment]
Thank you very much for your response and kind comments.

1. The suggestion to utilize GPUs is highly appreciated
2. I'm grateful for your guidance. I intend to explore machine learning processes using a computer with GPUs while executing the fit process on a computer without GPUs. Would it be possible to incorporate this functionality in an upcoming update?
3.Your insights regarding cluster interpretation based on varying numbers in your paper are intriguing . I think Sankey diagram seems to be a suitable visualization method? Link:https://medium.com/@cbkwgl/sankey-diagrams-in-python-fc9673465ccb

Thank you again for your comments.
Ayumu

**Comment by marcovarrone** [comment]
Thank you very much @ayumatsubo ! I also thought about Sankey diagrams and I used them in my lab meeting today :) a colleague even suggested adding a dendrogram next to it, so let's what I will be able to come up with!

Regarding 2), it's already possible. You just need to run `gmm.trainer_params['accelerator'] = 'cpu'` where `gmm` is the fitted `tl.Cluster`.

If you are using `tl.ClusterAutoK` you can run `autok.best_models[N_CLUSTERS].trainer_params['accelerator'] = 'cpu'` where `autok.best_models[N_CLUSTERS]` is the gmm with the highest likelihood for that specific number of clusters.

I wrote the code by memory, so there may be some mistakes, in case you are still having problems I can check the precise code.

Anyway, as soon as I will be able to increase the supported versions for PyTorch and PyTorch Lightning, that line of code will not be required and it will be done all automatically (hopefully!).

**Comment by ayumatsubo** [comment]
Thank you always for your support.

regarding 2) This information was very helpful, and it worked very well to other institution sample.

I'm looking forward to future advancements.

Thanks.
