### ISSUE TITLE
bugs in cc.gr.diff_nhood_enrichment

### ISSUE THREAD

**Issue by SGIlabes** [marcovarrone/cellcharter#22]
### Report

Thank you for developing an excellent tool. However, I've encountered a minor issue with the cc.pl.diff_nhood_enrichment function.

Initially, I used the cc.gr.diff_nhood_enrichment function as follows:

cc.gr.diff_nhood_enrichment(
    data,
    cluster_key='cell_type',
    condition_key='DFS',
    library_key='fov_id',
    pvalues=True,
    n_jobs=15,
    n_perms=10
)

Subsequently, I used the cc.pl.diff_nhood_enrichment function:

cc.pl.diff_nhood_enrichment(
    data,
    cluster_key='cell_type',
    condition_key='DFS',
    condition_groups=['No', 'Yes'],
    annotate=True,
    figsize=(7,7),
    significance=0.01
)

I expected the result to represent "DFS Yes - DFS No". However, the initial output appeared to show "DFS No - DFS Yes".

Moreover, when I modified the condition_groups from ['No', 'Yes'] to ['Yes', 'No'], the direction of the results continued to change, even though the rest of the code remained the same.

And I have one more question.
In cc.pl.diff_nhood_enrichment,  is it correct that row_groups are target and col_groups are source ?

 
### Version information

----
anndata             0.10.3
cellcharter         0.2.0
dill                0.3.7
matplotlib          3.8.2
numpy               1.26.2
pandas              2.1.4
scanpy              1.9.6
scvi                1.0.4
session_info        1.0.0
squidpy             1.3.1
torch               1.12.1
-----
PIL                         9.4.0
absl                        NA
affine                      2.4.0
aiobotocore                 2.5.4
aiohttp                     3.9.1
aioitertools                0.11.0
aiosignal                   1.3.1
annotated_types             0.6.0
anyio                       NA
appnope                     0.1.3
arrow                       1.3.0
asciitree                   NA
...
Python 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:35:25) [Clang 16.0.6 ]
macOS-14.1.2-arm64-arm-64bit
-----
Session information updated at 2024-01-19 16:08
Output is truncated. View as a [scrollable element](command:cellOutput.enableScrolling?fe343404-9929-490b-90cb-2ba46f5ac561) or open in a [text editor](command:workbench.action.openLargeOutput?fe343404-9929-490b-90cb-2ba46f5ac561). Adjust cell output [settings](command:workbench.action.openSettings?%5B%22%40tag%3AnotebookOutputLayout%22%5D)...

**Comment by marcovarrone** [comment]
Hi @SGIlabes, thank you very much for the feedback! 
I would have not been able to catch the bug by myself :)

The fix is going to be available with the next release (v0.2.1) very soon. In the meantime if you need the fix right now you can clone the repository to have the development version.

Regarding the source-target question. In the paper it's different but in the official library the rows are the source and the columns are the targets. In fact, if you look at the clusters C8 (B-follicle in pink) and C7 (marginal zone in blue)
![image](https://github.com/CSOgroup/cellcharter/assets/9199935/2adf0a88-ad13-4bc7-8940-f6355e195ea3)
The neighborhood enrichment between C8 and C7 is higher (because the germinal center is surrounded by the marginal zone most of the time) than between C7 and C8 (because the marginal zone is in contact with other clusters on the other side compared to the B follicle).

I hope it's clear!
![image](https://github.com/CSOgroup/cellcharter/assets/9199935/251c2767-e8ce-4f0b-8052-2018afe6c12e)

**Comment by SGIlabes** [comment]
Thank you so much for the example explanation. It allowed me to understand the concept very clearly. I'm looking forward to utilizing your tool for some useful analysis. Your guidance has been incredibly beneficial.

**Comment by milddaa** [comment]
Hello! Another question on cc.pl.diff_nhood_enrichment plots. If the title of the plot is "Control vs Condition" (in this order), am I correct in assuming that green color means the two clusters are MORE proximal to each other in Condition than Control, and purple means they are LESS proximal in Condition than Control? Thank you in advance!

**Comment by marcovarrone** [comment]
Hi @milddaa, yes you are correct. 

The first term in the title is what is considered "observed" (control), while the second term is what is considered "expected" (condition).
- Having lower values (green) means that the cells in the two clusters are adjacent more often in the expected (condition) than in the observed (control). 
- Having higher values (purple), means that the cells in the two clusters are adjacent more often in the observed (control) than in the expected (condition).

Let me know if it makes sense and matches what you expect. I have used and tested the function many times but as you can tell there is always a chance of having a bug (as in any software!).
