### ISSUE TITLE
Using cc.gr.nhood_enrichment to compare spatial clusters localisation to histological zones and cc.gr.diff_nhood_enrichment with more than two conditions

### ISSUE THREAD

**Issue by antonncheeseman** [marcovarrone/cellcharter#26]
### Description of feature

Hi,

We've been starting to implement this very useful package and overall have had very few issues with it. There are a couple of features which we would greatly appreciate though.

The first is a way to use cc.gr.diff_nhood_enrichment with the computationally defined spatial clusters/neighborhoods and pre-defined histological zones, to analyse the localisation of neighborhoods to histological zones already identified. We noticed that you had defined zones of the mouse spleen in the CODEX dataset by masking (which can easily be applied to the cells in the adata.obs object) but had not done any direct comparisons of neighborhoods to zones and how the localisation of neighborhoods to zones change in the lupus vs healthy mice.

Second is the ability to make comparisons between multiple condition groups in cc.gr.diff_nhood_enrichment (e.g. time course data: naive vs time _x_, naive vs time _y_, time _x_ vs time _y_). As is, when running with >2 conditions present in the condition key, the computation of p value iterations completes but then returns "ValueError: The truth value of a DataFrame is ambiguous." I would presume that running this on multiple filtered datasets independently would be possible but this is quite inconvenient for data handling when the number of condition groups scales.

If these features are possible to add without too much bother, it would be incredibly helpful. Many thanks!

**Comment by marcovarrone** [comment]
Hi @antonncheeseman, thank you very much for the feedback!

The annotations of the zones for the CODEX dataset come directly from the [original paper](https://doi.org/10.1016/j.cell.2018.07.010). The problem with those annotations (and the reason why we didn't use them other than a simple visual comparison) is that they have only been roughly sketched by the pathologists, so they are not extremely accurate. And even more importantly, they were provided only for the 3 normal samples.
Independently of the CODEX annotations, one could transfer the annotations to the cells, as you suggested. However, the neighborhood enrichment has been designed to measure the adjacency between two disjoint clusters, that do not have cells in common. This would not be true for spatial domains against zones, because if they match, they would cover the same cells. But one could compute the adjusted rand index similarly to what we do in the benchmarking.
If you would like to have a way to draw polygons and transfer the annotations to cells, in theory, it's possible, but it may require quite some time (especially the drawing part, the second step is easy).

Let me know if I understood your question and if I answered it :)

The second problem is probably a bug, so I'll look into it and let you know!

**Comment by antonncheeseman** [comment]
Hi,

This makes perfect sense, thank you for the very clear explanation regarding issue 1. With my IMC dataset, I have already undertaken the (incredibly painstaking) process of annotating images with spatial domains in QuPath and have transferred the annotations, so that's okay.

If issue 2 could be resolved, this would be great thanks. If we can help with this by providing more information privately, we'd be happy to. Many thanks!

**Comment by marcovarrone** [comment]
Fixed by #45
