### ISSUE TITLE
Installation of cellcharter

### ISSUE THREAD

**Issue by alirezaah98** [marcovarrone/cellcharter#29]
### Report

I have been trying to set a new environment for cell charter and install all the dependencies but it seems that scvi-tools has beeen updated and is not compatible with torch version required for cell charter, I would appreciate it if you could help me with it as the main problem is scvitools which automatically updates the torch to version 2.2 :)

**Comment by marcovarrone** [comment]
Hi @alirezaah98, after a long time struggling I finally understood what was the problem.
It wasn't because of scvi-tools itself, but a dependency of scvi-tools (pyro-ppl).
So, in the installation procedure, you can replace `pip install scvi-tools` with `pip install pyro-ppl==1.8.6 scvi-tools==0.20.3`.

Tomorrow morning I will push a change to the README file and close this issue, but thank you very much for the feedback.
It has been very useful to understand the problem :)
