### ISSUE TITLE
Nothing in PyPI repo?

### ISSUE THREAD

**Issue by qu4drupole** [marcovarrone/cellcharter#5]
### Report

Very excited to try the module! I installed cellcharter from PyPI. Looked like it just installed some dependencies, and there were no errors, but I don't see any methods or classes in the module. 

I first installed pytorch for CUDA 11.6, then `pip install cellcharter`. Should I be using this GitHub repo instead?

### Version information

-----
cellcharter         0.0.1
session_info        1.0.0
-----
anndata             0.8.0
cython_runtime      NA
dateutil            2.8.2
h5py                3.8.0
natsort             8.2.0
numpy               1.24.1
packaging           23.0
pandas              1.5.3
pytz                2022.7.1
scipy               1.10.0
six                 1.16.0
zoneinfo            NA
-----
Python 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
Linux-4.18.0-348.20.1.el8_5.x86_64-x86_64-with-glibc2.28
-----

**Comment by marcovarrone** [comment]
Hi @qu4drupole, thank you for your interest and the report!
The problem comes from the fact that some dependencies of CellCharter do not support Python 3.11. The latest version of CellCharter in PyPI is currently 0.1.0, while you can see that it installed the 0.0.1 version in your environment.

This is because the (basically empty) version 0.0.1 didn't have the requirement of Python < 3.11.0. So once pip saw that you have Python 3.11, it installed the latest version that supports it.

Your quickest solution would be to create an environment that has Python 3.10, for example with the following code:
`conda create -n ENVIRONMENT_NAME python=3.10`.

I will soon add a warning in the documentation or find a way to prevent pip from installing automatically the 0.0.1 version, but to give an error instead.

Let me know if it solved your problem!

**Comment by qu4drupole** [comment]
The new install looks good. Version 0.1.1. I'm excited to try it out!
